#port => default 8080 => 보안 설정(AWS) : port 허용 
# 8080 / 1521 / 3306 (MySql , MariaDB) 
# MVC 설정 
server:
  port: 8080

spring:
  mvc:
   view:
      prefix: /WEB-INF/views/
      suffix: .jsp
  datasource:
     url: jdbc:mysql://localhost:3306/mydb?serverTimezone=UTC
     username: root
     password: happy
     driver-class-name: com.mysql.cj.jdbc.Driver
  #ai:
    #google:
      #genai:
        #api-key:
  mail:
    host: smtp.naver.com
    port: 587
    username: hotsushi3021@naver.com
    password: #smtp key
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
mybatis:
  type-aliases-package: com.sist.web.vo
  mapper-locations: mybatis/mapper/*.xml

# 프로시저 / 트리거 / 함수 
# JPA => JOIN => CRUD 
# WebSocket 설정 / Kafka설정 / MSA 설정 
# Security : 람다식 
 
